<?xml version="1.0"?>
<robot name="racecar" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find bobcat_description)/urdf/macros.xacro" />


  <xacro:property name="PI" value="3.1415926835897931"/>
<!--  <xacro:property name="base_height" value="0"/> -->
  <xacro:property name="base_height" value="0.4"/>
  <xacro:property name="base_mass" value="1000"/>
  <xacro:property name="base_mass_ixx" value="30"/>
  <xacro:property name="base_mass_iyy" value="500"/>
  <xacro:property name="base_mass_izz" value="550"/>
  <xacro:property name="base_mass_ixz" value="-15"/>
  <xacro:property name="tyre_x" value="0.76"/>
  <xacro:property name="tyre_y" value="0.5"/>
  <xacro:property name="tyre_length" value="0.229"/>
  <xacro:property name="tyre_height" value="-0.696"/>
  <xacro:property name="tyre_r" value="0.22"/>
  <xacro:property name="tyre_radius" value="0.22"/>
  <xacro:property name="tyre_mass" value="3"/>
  <xacro:property name="tyre_mass_ixx" value="20"/>
  <xacro:property name="tyre_mass_iyy" value="20"/>
  <xacro:property name="tyre_mass_izz" value="50"/>
  <xacro:property name="car_height" value="0.6"/>
  <xacro:property name="car_width" value="1.0"/>
  <xacro:property name="car_length" value="1.54"/>
  <xacro:property name="camera_box" value="0.1"/>
  <xacro:property name="str_length" value="0.01"/>
  <xacro:property name="str_radius" value="0.1"/>
  <xacro:property name="str_angle" value="0.5"/>
  <xacro:property name="tyre_origin">
	<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
  </xacro:property>
  <xacro:property name="tyre_origin_2">
        <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
  </xacro:property>
  <xacro:property name="tyre_origin_3">
        <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
  </xacro:property>



  <!-- Add chassis and it's inertia link -->
  <link name="base_link">
    <collision>
	<origin xyz="0 0 ${base_height}" rpy= "0 0 0"/>
        <geometry> 
            <box size="${car_length} ${car_width} ${car_height}"/>
        </geometry>
    </collision>
    <visual>
      <!--xacro:chassis_geometry/-->  
      <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
      <geometry>
	 <!--mesh><uri>file://kappa_scene.dae</uri></mesh-->
        <box size="${car_length} ${car_width} ${car_height}"/>
      </geometry>
      <material name="blue" />
    </visual>
  </link>

  <link name="main_mass">
    <inertial>
      <!--xacro:chassis_inertial_params /-->
      <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
      <mass value="${base_mass}" />
      <inertia
          ixx="${base_mass_ixx}"  ixy="0.000000" ixz="${base_mass_ixz}"
          iyy="${base_mass_iyy}"  iyz="0.000000"
          izz="${base_mass_izz}"/>
      </inertial>
      <dampingFactor>0.1</dampingFactor>
  </link>

  <joint name="inertia_joint" type="fixed">
    <parent link="base_link" />
    <child link="main_mass" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>





  <!-- Left Rear Wheel -->
  <link name="left_rear_wheel">
    <collision>
      <xacro:insert_block name="tyre_origin"/>
      <!--xacro:left_wheels_collision_geometry/-->
      <geometry>
        <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
      </geometry>
    </collision>
    <visual>
      <!--xacro:left_rear_wheel_geometry /-->
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
        <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
      </geometry>
      <material name="black" />
    </visual>
    <inertial>
      <!--xacro:left_wheels_inertial_params /-->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${tyre_mass}"/>
      <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
    </inertial>
  </link>

  <joint name="left_rear_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="left_rear_wheel" />
<!-- here y is PI as the car will be mounted in the same direction as the right wheel and that somewhat seems wrong. When you turn this back for whatever reason remember to set axis to +1 as it will turn in the wrong direction otherwise -->
    <origin xyz="${-tyre_x} ${car_width/2 + tyre_length/2} ${tyre_r}" rpy="0 0 ${PI}"/>
    <axis xyz="0 -1 0" />
    <dynamics damping="0.2"/>
    <limit effort="100000" velocity="100" />
    <joint_properties damping="0.0" friction="0.0" />
  </joint>
  <!-- this transmission is added to connect to wheel effort controller! dont delete"-->
  <xacro:wheel_transmission name="left_rear_wheel" />





  <!-- Right Rear Wheel -->
  <link name="right_rear_wheel">
    <collision>
      <!--xacro:right_wheels_collision_geometry /-->
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
        <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
      </geometry>
    </collision>
    <visual>
      <xacro:insert_block name="tyre_origin"/>
      <!--xacro:right_rear_wheel_geometry /-->
      <geometry>
        <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
      </geometry>
      <material name="black" />
    </visual>
    <inertial>
      <!--xacro:right_wheels_inertial_params /-->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${tyre_mass}"/>
      <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
    </inertial>
  </link>

  <joint name="right_rear_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="right_rear_wheel" />
    <origin xyz="${-tyre_x} ${-car_width/2 - tyre_length/2} ${tyre_r}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2"/>
    <limit effort="100000" velocity="100" />
    <joint_properties damping="0.0" friction="0.0" />
  </joint>
  <!-- this transmission is added to connect to wheel effort controller! dont delete"-->
  <xacro:wheel_transmission name="right_rear_wheel" />



  <!-- Left Steering Hinge -->
  <link name="left_steering_hinge">
    <collision>
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
        <cylinder length="${str_length}" radius="${str_radius}"/>
      </geometry>
    </collision>
    <visual>
      <!--xacro:left_steering_hinge_geometry /-->
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
        <cylinder length="${str_length}" radius="${str_radius}"/>
      </geometry>
      <material name="grey" />
    </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
    </inertial>
  </link>

  <joint name="left_steering_hinge_joint" type="revolute">
    <parent link="base_link" />
    <child link="left_steering_hinge" />
    <origin xyz="${tyre_x} ${car_width/2 + str_length/2} ${tyre_r}" rpy="0 0 ${PI}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="1.0"/>
  </joint>
  <!-- this transmission is added to connect to wheel effort controller! dont delete"-->
  <xacro:steering_hinge_transmission name="left_steering_hinge" />




  <!-- Right Steering Hinge -->
  
  <link name="right_steering_hinge">
    <collision>
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
        <cylinder length="${str_length}" radius="${str_radius}"/>
      </geometry>
    </collision>
    <visual>
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
        <cylinder length="${str_length}" radius="${str_radius}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="10.00"/>
      <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
    </inertial>
  </link>

  <joint name="right_steering_hinge_joint" type="revolute">
    <parent link="base_link" />
    <child link="right_steering_hinge" />
    <origin xyz="${tyre_x} ${-car_width/2 - str_length/2} ${tyre_r}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="1.0"/>
  </joint>
  <!-- this transmission is added to connect to wheel effort controller! dont delete"-->
  <xacro:steering_hinge_transmission name="right_steering_hinge" />





  <!-- Left Front Wheel -->
  
  <link name="left_front_wheel">
    <collision>
      <!--xacro:left_wheels_collision_geometry /-->
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
      </geometry>
    </collision>
    <visual>
      <!--xacro:left_front_wheel_geometry /-->
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
      </geometry>
      <material name="black" />
    </visual>
    <inertial>
      <!--xacro:left_wheels_inertial_params /-->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${tyre_mass}"/>
      <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
    </inertial>
  </link>

  <joint name="left_front_wheel_joint" type="continuous">
    <parent link="left_steering_hinge" />
    <child link="left_front_wheel" />
    <origin xyz="0 ${-str_length/2 - tyre_length/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0" />
    <dynamics damping="0.1"/>
    <limit effort="10000" velocity="100" />
    <joint_properties damping="0.0" friction="0.0" />
  </joint>
  <!-- this transmission is added to connect to wheel effort controller! dont delete"-->
  <xacro:wheel_transmission name="left_front_wheel" />



  <!-- Right Front Wheel -->
  <link name="right_front_wheel">
    <collision>
      <!--xacro:right_wheels_collision_geometry /-->
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
        <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
      </geometry>
    </collision>
    <visual>
      <!--xacro:right_front_wheel_geometry /-->
      <xacro:insert_block name="tyre_origin"/>
      <geometry>
        <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
      </geometry>
      <material name="black" />
    </visual>
    <inertial>
      <!--xacro:right_wheels_inertial_params /-->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${tyre_mass}"/>
      <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/> 
    </inertial>
  </link>

  <joint name="right_front_wheel_joint" type="continuous">
    <parent link="right_steering_hinge" />
    <child link="right_front_wheel" />
    <origin xyz="0 ${-str_length/2 - tyre_length/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0" />
    <dynamics damping="0.1"/>
    <limit effort="10000" velocity="100" />
    <joint_properties damping="0.0" friction="0.0" />
  </joint>
  <!-- this transmission is added to connect to wheel effort controller! dont delete"-->
  <xacro:wheel_transmission name="right_front_wheel" />

<!-- Add IMU -->
<link name="imu_link">
  <inertial>
    <mass value="0.001"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
  </inertial>
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <box size="0.001 0.001 0.001"/>
    </geometry>
  </visual>
  <collision>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <box size=".001 .001 .001"/>
    </geometry>
  </collision>
</link>

  <joint name="imu_joint" type="fixed">
    <axis xyz="1 0 0"/> <!-- 0 1 0 -->
    <origin xyz="0 0 0.19"/>
    <parent link="base_link"/>
    <child link="imu_link"/>
  </joint>

  <!-- Add Hokuyo laser scanner -->

  <link name="laser">
    <inertial>
      <xacro:hokuyo_inertial_params />
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://bobcat_description/meshes/hokuyo.dae"/>
        <material name="grey" />
      </geometry>
    </visual>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="${tyre_x + 0.1} 0 ${car_height - tyre_r/2}" />
    <parent link="base_link" />
    <child link="laser" />
    <axis xyz="0 0 1" />
  </joint>


  <!-- zed camera -->
  <link name="zed_camera_link">
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.033 0.175 0.030"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.033 0.175 0.030"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="zed_camera_joint" type="fixed">
    <origin xyz="${tyre_x} 0 ${car_height + tyre_r/2}" />
    <parent link="base_link"/>
    <child link="zed_camera_link"/>
    <axis xyz="0 0 1" />
    <!--limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0" /-->
  </joint>


  <!-- zed camera lenses -->
  <!-- It seems these have to have a non-zero mass to have a camera attached? -->
  <link name="camera_link"><!-- this needs to match the name in zed_wrapper/zed_tf.launch -->
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  <link name="zed_camera_right_link">
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="zed_camera_left_joint" type="fixed">
    <origin xyz="0 0.06 0" rpy="0 0 0"/>
    <parent link="zed_camera_link"/>
    <child link="camera_link"/>
    <axis xyz="0 0 1" />
  </joint>
  <joint name="zed_camera_right_joint" type="fixed">
    <origin xyz="0 -0.06 0" rpy="0 0 0"/>
    <parent link="zed_camera_link"/>
    <child link="zed_camera_right_link"/>
    <axis xyz="0 0 1" />
  </joint>

  <!-- Add the remaining xacros -->

  <xacro:include filename="$(find bobcat_description)/urdf/bobcat.gazebo" />
  <xacro:include filename="$(find bobcat_description)/urdf/materials.xacro" />

</robot>

